# Generated by Django 5.1.3 on 2024-12-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('humedad', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='myapp.planta')),
            ],
        ),
    ]
